/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PaymentMethodsRouteImport } from './routes/payment-methods'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as PreviewDothtmlRouteImport } from './routes/preview[.]html'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BookIndexRouteImport } from './routes/book/index'
import { Route as BookConfirmationRouteImport } from './routes/book/confirmation'
import { Route as BookDateRouteImport } from './routes/book/date'
import { Route as BookFocusRouteImport } from './routes/book/focus'
import { Route as BookNotesRouteImport } from './routes/book/notes'
import { Route as BookPaymentRouteImport } from './routes/book/payment'
import { Route as BookReviewRouteImport } from './routes/book/review'
import { Route as BookTimeRouteImport } from './routes/book/time'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as MessagesThreadIdRouteImport } from './routes/messages/$threadId'
import { Route as MessagesChatRouteImport } from './routes/messages/chat'
import { Route as PlansIndexRouteImport } from './routes/plans/index'
import { Route as PlansCheckoutRouteImport } from './routes/plans/checkout'
import { Route as PlansConfirmationRouteImport } from './routes/plans/confirmation'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesResourceIdRouteImport } from './routes/resources/$resourceId'
import { Route as SessionsRescheduleRouteImport } from './routes/sessions/reschedule'
import { Route as WellnessHealingIndexRouteImport } from './routes/wellness-healing/index'
import { Route as WellnessHealingSplatRouteImport } from './routes/wellness-healing/$'
import { Route as ResourcesResourceIdPracticeRouteImport } from './routes/resources/$resourceId.practice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentMethodsRoute = PaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewDothtmlRoute = PreviewDothtmlRouteImport.update({
  id: '/preview.html',
  path: '/preview.html',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookConfirmationRoute = BookConfirmationRouteImport.update({
  id: '/book/confirmation',
  path: '/book/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDateRoute = BookDateRouteImport.update({
  id: '/book/date',
  path: '/book/date',
  getParentRoute: () => rootRouteImport,
} as any)
const BookFocusRoute = BookFocusRouteImport.update({
  id: '/book/focus',
  path: '/book/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const BookNotesRoute = BookNotesRouteImport.update({
  id: '/book/notes',
  path: '/book/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const BookPaymentRoute = BookPaymentRouteImport.update({
  id: '/book/payment',
  path: '/book/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const BookReviewRoute = BookReviewRouteImport.update({
  id: '/book/review',
  path: '/book/review',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTimeRoute = BookTimeRouteImport.update({
  id: '/book/time',
  path: '/book/time',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MessagesRoute,
} as any)
const MessagesThreadIdRoute = MessagesThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => MessagesRoute,
} as any)
const MessagesChatRoute = MessagesChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => MessagesRoute,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansCheckoutRoute = PlansCheckoutRouteImport.update({
  id: '/plans/checkout',
  path: '/plans/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansConfirmationRoute = PlansConfirmationRouteImport.update({
  id: '/plans/confirmation',
  path: '/plans/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesResourceIdRoute = ResourcesResourceIdRouteImport.update({
  id: '/$resourceId',
  path: '/$resourceId',
  getParentRoute: () => ResourcesRoute,
} as any)
const SessionsRescheduleRoute = SessionsRescheduleRouteImport.update({
  id: '/reschedule',
  path: '/reschedule',
  getParentRoute: () => SessionsRoute,
} as any)
const WellnessHealingIndexRoute = WellnessHealingIndexRouteImport.update({
  id: '/wellness-healing/',
  path: '/wellness-healing/',
  getParentRoute: () => rootRouteImport,
} as any)
const WellnessHealingSplatRoute = WellnessHealingSplatRouteImport.update({
  id: '/wellness-healing/$',
  path: '/wellness-healing/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesResourceIdPracticeRoute =
  ResourcesResourceIdPracticeRouteImport.update({
    id: '/practice',
    path: '/practice',
    getParentRoute: () => ResourcesResourceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/preview': typeof PreviewRoute
  '/preview.html': typeof PreviewDothtmlRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/sessions': typeof SessionsRouteWithChildren
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/book/confirmation': typeof BookConfirmationRoute
  '/book/date': typeof BookDateRoute
  '/book/focus': typeof BookFocusRoute
  '/book/notes': typeof BookNotesRoute
  '/book/payment': typeof BookPaymentRoute
  '/book/review': typeof BookReviewRoute
  '/book/time': typeof BookTimeRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/messages/chat': typeof MessagesChatRoute
  '/plans/checkout': typeof PlansCheckoutRoute
  '/plans/confirmation': typeof PlansConfirmationRoute
  '/profile/edit': typeof ProfileEditRoute
  '/resources/$resourceId': typeof ResourcesResourceIdRouteWithChildren
  '/sessions/reschedule': typeof SessionsRescheduleRoute
  '/wellness-healing/$': typeof WellnessHealingSplatRoute
  '/book/': typeof BookIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/plans/': typeof PlansIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/wellness-healing/': typeof WellnessHealingIndexRoute
  '/resources/$resourceId/practice': typeof ResourcesResourceIdPracticeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/preview': typeof PreviewRoute
  '/preview.html': typeof PreviewDothtmlRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/book/confirmation': typeof BookConfirmationRoute
  '/book/date': typeof BookDateRoute
  '/book/focus': typeof BookFocusRoute
  '/book/notes': typeof BookNotesRoute
  '/book/payment': typeof BookPaymentRoute
  '/book/review': typeof BookReviewRoute
  '/book/time': typeof BookTimeRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/messages/chat': typeof MessagesChatRoute
  '/plans/checkout': typeof PlansCheckoutRoute
  '/plans/confirmation': typeof PlansConfirmationRoute
  '/profile/edit': typeof ProfileEditRoute
  '/resources/$resourceId': typeof ResourcesResourceIdRouteWithChildren
  '/sessions/reschedule': typeof SessionsRescheduleRoute
  '/wellness-healing/$': typeof WellnessHealingSplatRoute
  '/book': typeof BookIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/plans': typeof PlansIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/wellness-healing': typeof WellnessHealingIndexRoute
  '/resources/$resourceId/practice': typeof ResourcesResourceIdPracticeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/home': typeof HomeRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/preview': typeof PreviewRoute
  '/preview.html': typeof PreviewDothtmlRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/sessions': typeof SessionsRouteWithChildren
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/book/confirmation': typeof BookConfirmationRoute
  '/book/date': typeof BookDateRoute
  '/book/focus': typeof BookFocusRoute
  '/book/notes': typeof BookNotesRoute
  '/book/payment': typeof BookPaymentRoute
  '/book/review': typeof BookReviewRoute
  '/book/time': typeof BookTimeRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/messages/chat': typeof MessagesChatRoute
  '/plans/checkout': typeof PlansCheckoutRoute
  '/plans/confirmation': typeof PlansConfirmationRoute
  '/profile/edit': typeof ProfileEditRoute
  '/resources/$resourceId': typeof ResourcesResourceIdRouteWithChildren
  '/sessions/reschedule': typeof SessionsRescheduleRoute
  '/wellness-healing/$': typeof WellnessHealingSplatRoute
  '/book/': typeof BookIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/plans/': typeof PlansIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/wellness-healing/': typeof WellnessHealingIndexRoute
  '/resources/$resourceId/practice': typeof ResourcesResourceIdPracticeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/help'
    | '/home'
    | '/intake'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/payment-methods'
    | '/preview'
    | '/preview.html'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/resources'
    | '/sessions'
    | '/subscription'
    | '/terms'
    | '/book/confirmation'
    | '/book/date'
    | '/book/focus'
    | '/book/notes'
    | '/book/payment'
    | '/book/review'
    | '/book/time'
    | '/messages/$threadId'
    | '/messages/chat'
    | '/plans/checkout'
    | '/plans/confirmation'
    | '/profile/edit'
    | '/resources/$resourceId'
    | '/sessions/reschedule'
    | '/wellness-healing/$'
    | '/book/'
    | '/messages/'
    | '/plans/'
    | '/resources/'
    | '/wellness-healing/'
    | '/resources/$resourceId/practice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/help'
    | '/home'
    | '/intake'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/payment-methods'
    | '/preview'
    | '/preview.html'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/sessions'
    | '/subscription'
    | '/terms'
    | '/book/confirmation'
    | '/book/date'
    | '/book/focus'
    | '/book/notes'
    | '/book/payment'
    | '/book/review'
    | '/book/time'
    | '/messages/$threadId'
    | '/messages/chat'
    | '/plans/checkout'
    | '/plans/confirmation'
    | '/profile/edit'
    | '/resources/$resourceId'
    | '/sessions/reschedule'
    | '/wellness-healing/$'
    | '/book'
    | '/messages'
    | '/plans'
    | '/resources'
    | '/wellness-healing'
    | '/resources/$resourceId/practice'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/help'
    | '/home'
    | '/intake'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/payment-methods'
    | '/preview'
    | '/preview.html'
    | '/privacy'
    | '/profile'
    | '/register'
    | '/resources'
    | '/sessions'
    | '/subscription'
    | '/terms'
    | '/book/confirmation'
    | '/book/date'
    | '/book/focus'
    | '/book/notes'
    | '/book/payment'
    | '/book/review'
    | '/book/time'
    | '/messages/$threadId'
    | '/messages/chat'
    | '/plans/checkout'
    | '/plans/confirmation'
    | '/profile/edit'
    | '/resources/$resourceId'
    | '/sessions/reschedule'
    | '/wellness-healing/$'
    | '/book/'
    | '/messages/'
    | '/plans/'
    | '/resources/'
    | '/wellness-healing/'
    | '/resources/$resourceId/practice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  HomeRoute: typeof HomeRoute
  IntakeRoute: typeof IntakeRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PaymentMethodsRoute: typeof PaymentMethodsRoute
  PreviewRoute: typeof PreviewRoute
  PreviewDothtmlRoute: typeof PreviewDothtmlRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SessionsRoute: typeof SessionsRouteWithChildren
  SubscriptionRoute: typeof SubscriptionRoute
  TermsRoute: typeof TermsRoute
  BookConfirmationRoute: typeof BookConfirmationRoute
  BookDateRoute: typeof BookDateRoute
  BookFocusRoute: typeof BookFocusRoute
  BookNotesRoute: typeof BookNotesRoute
  BookPaymentRoute: typeof BookPaymentRoute
  BookReviewRoute: typeof BookReviewRoute
  BookTimeRoute: typeof BookTimeRoute
  PlansCheckoutRoute: typeof PlansCheckoutRoute
  PlansConfirmationRoute: typeof PlansConfirmationRoute
  WellnessHealingSplatRoute: typeof WellnessHealingSplatRoute
  BookIndexRoute: typeof BookIndexRoute
  PlansIndexRoute: typeof PlansIndexRoute
  WellnessHealingIndexRoute: typeof WellnessHealingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-methods': {
      id: '/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof PaymentMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview.html': {
      id: '/preview.html'
      path: '/preview.html'
      fullPath: '/preview.html'
      preLoaderRoute: typeof PreviewDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/': {
      id: '/book/'
      path: '/book'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/confirmation': {
      id: '/book/confirmation'
      path: '/book/confirmation'
      fullPath: '/book/confirmation'
      preLoaderRoute: typeof BookConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/date': {
      id: '/book/date'
      path: '/book/date'
      fullPath: '/book/date'
      preLoaderRoute: typeof BookDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/focus': {
      id: '/book/focus'
      path: '/book/focus'
      fullPath: '/book/focus'
      preLoaderRoute: typeof BookFocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/notes': {
      id: '/book/notes'
      path: '/book/notes'
      fullPath: '/book/notes'
      preLoaderRoute: typeof BookNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/payment': {
      id: '/book/payment'
      path: '/book/payment'
      fullPath: '/book/payment'
      preLoaderRoute: typeof BookPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/review': {
      id: '/book/review'
      path: '/book/review'
      fullPath: '/book/review'
      preLoaderRoute: typeof BookReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/time': {
      id: '/book/time'
      path: '/book/time'
      fullPath: '/book/time'
      preLoaderRoute: typeof BookTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/messages/$threadId': {
      id: '/messages/$threadId'
      path: '/$threadId'
      fullPath: '/messages/$threadId'
      preLoaderRoute: typeof MessagesThreadIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/messages/chat': {
      id: '/messages/chat'
      path: '/chat'
      fullPath: '/messages/chat'
      preLoaderRoute: typeof MessagesChatRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/plans/': {
      id: '/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/checkout': {
      id: '/plans/checkout'
      path: '/plans/checkout'
      fullPath: '/plans/checkout'
      preLoaderRoute: typeof PlansCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/confirmation': {
      id: '/plans/confirmation'
      path: '/plans/confirmation'
      fullPath: '/plans/confirmation'
      preLoaderRoute: typeof PlansConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/$resourceId': {
      id: '/resources/$resourceId'
      path: '/$resourceId'
      fullPath: '/resources/$resourceId'
      preLoaderRoute: typeof ResourcesResourceIdRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/sessions/reschedule': {
      id: '/sessions/reschedule'
      path: '/reschedule'
      fullPath: '/sessions/reschedule'
      preLoaderRoute: typeof SessionsRescheduleRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/wellness-healing/': {
      id: '/wellness-healing/'
      path: '/wellness-healing'
      fullPath: '/wellness-healing/'
      preLoaderRoute: typeof WellnessHealingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellness-healing/$': {
      id: '/wellness-healing/$'
      path: '/wellness-healing/$'
      fullPath: '/wellness-healing/$'
      preLoaderRoute: typeof WellnessHealingSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$resourceId/practice': {
      id: '/resources/$resourceId/practice'
      path: '/practice'
      fullPath: '/resources/$resourceId/practice'
      preLoaderRoute: typeof ResourcesResourceIdPracticeRouteImport
      parentRoute: typeof ResourcesResourceIdRoute
    }
  }
}

interface MessagesRouteChildren {
  MessagesThreadIdRoute: typeof MessagesThreadIdRoute
  MessagesChatRoute: typeof MessagesChatRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesThreadIdRoute: MessagesThreadIdRoute,
  MessagesChatRoute: MessagesChatRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface ProfileRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface ResourcesResourceIdRouteChildren {
  ResourcesResourceIdPracticeRoute: typeof ResourcesResourceIdPracticeRoute
}

const ResourcesResourceIdRouteChildren: ResourcesResourceIdRouteChildren = {
  ResourcesResourceIdPracticeRoute: ResourcesResourceIdPracticeRoute,
}

const ResourcesResourceIdRouteWithChildren =
  ResourcesResourceIdRoute._addFileChildren(ResourcesResourceIdRouteChildren)

interface ResourcesRouteChildren {
  ResourcesResourceIdRoute: typeof ResourcesResourceIdRouteWithChildren
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesResourceIdRoute: ResourcesResourceIdRouteWithChildren,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface SessionsRouteChildren {
  SessionsRescheduleRoute: typeof SessionsRescheduleRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsRescheduleRoute: SessionsRescheduleRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  HomeRoute: HomeRoute,
  IntakeRoute: IntakeRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PaymentMethodsRoute: PaymentMethodsRoute,
  PreviewRoute: PreviewRoute,
  PreviewDothtmlRoute: PreviewDothtmlRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  SessionsRoute: SessionsRouteWithChildren,
  SubscriptionRoute: SubscriptionRoute,
  TermsRoute: TermsRoute,
  BookConfirmationRoute: BookConfirmationRoute,
  BookDateRoute: BookDateRoute,
  BookFocusRoute: BookFocusRoute,
  BookNotesRoute: BookNotesRoute,
  BookPaymentRoute: BookPaymentRoute,
  BookReviewRoute: BookReviewRoute,
  BookTimeRoute: BookTimeRoute,
  PlansCheckoutRoute: PlansCheckoutRoute,
  PlansConfirmationRoute: PlansConfirmationRoute,
  WellnessHealingSplatRoute: WellnessHealingSplatRoute,
  BookIndexRoute: BookIndexRoute,
  PlansIndexRoute: PlansIndexRoute,
  WellnessHealingIndexRoute: WellnessHealingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
